### ISSUE TITLE
Large Screen Issue with quick drop

### ISSUE THREAD

**Issue by DarrenHarrower** [RichTeaMan/Polytris#1]
When on a large screen pushing the down arrow moves the window down aswell as the object, then to try and move the screen back up it drops the object, ruined my highscore

**Comment by RichTeaMan** [comment]
Resizing should be smarter now.

**Comment by DarrenHarrower** [comment]
I would like to disagree with this as fixed, where was the independant test, appears to still be an issue on 1280x1024 resolution monitors.

**Comment by DarrenHarrower** [comment]
I retract my comment as test paramaters were unfair at 150% zoom
